# Generated by Django 6.0.6 on 2026-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLoteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de Lotería')),
                ('fecha', models.DateField(verbose_name='Fecha del Sorteo')),
            ],
        ),
    ]
